//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by BodyAnalyser.rc
//
#define IDD_ABOUTBOX                    100
#define IDR_MAINFRAME                   128
#define IDR_BODYANTYPE                  129
#define IDD_CAMERA_IMAGER               131
#define IDD_BSS_CONFIRM                 132
#define IDD_NOCURVMAP                   133
#define IDD_CURVMAP_CONFIRM             136
#define IDD_CANNY_PARAMS                137
#define IDD_CURVATURE_PROGRESS          138
#define IDD_HISTOGRAM                   141
#define IDB_BITMAP1                     145
#define IDD_HYST_THRESHOLDS             146
#define IDD_EVALUATION                  147
#define IDD_EVALUATION_REPORT           149
#define IDD_WRAP_MESH                   150
#define IDM_VIEWPOINTS                  997
#define IDC_ABOUT_TEXT                  999
#define IDC_CAMERA_0                    1003
#define IDC_MASKSIZE                    1004
#define IDC_UPPER_THRESHOLD             1005
#define IDC_LOWER_THRESHOLD             1006
#define IDC_LTHRES                      1009
#define IDC_HTHRES                      1010
#define IDC_SYMM_TYPE                   1016
#define IDC_DTHR                        1017
#define IDC_LTHR                        1018
#define IDC_HTHR                        1019
#define IDC_MINRIDGES                   1019
#define IDC_TRUEPOSITIVES               1021
#define IDC_FALSEPOSITIVES              1022
#define IDC_ALLPOSITIVES                1023
#define ID_FILE_INFO                    32771
#define ID_VIEW_PICEDIT                 32795
#define ID_VIEW_SELECTIONMODE           32806
#define ID_VIEW_VIEWINGMODE             32807
#define ID_FILE_IMPORT                  32817
#define ID_FILE_RELOAD                  32818
#define ID_VIEW_POINTCLOUD              32820
#define ID_VIEW_REFERENCEFRAME          32821
#define ID_VIEW_COORDINATEORIGIN        32822
#define ID_VIEW_CONNECTEDMESH_CAMERA0   32824
#define ID_VIEW_CONNECTEDMESH_CAMERA1   32825
#define ID_VIEW_CONNECTEDMESH_CAMERA2   32826
#define ID_VIEW_CONNECTEDMESH_CAMERA3   32827
#define ID_VIEW_CONNECTEDMESH_CAMERA4   32828
#define ID_VIEW_CONNECTEDMESH_CAMERA5   32829
#define ID_VIEW_CONNECTEDMESH_CAMERA6   32830
#define ID_VIEW_CONNECTEDMESH_CAMERA7   32831
#define ID_VIEW_CONNECTEDMESH_ALL       32832
#define ID_VIEW_CONNECTEDMESH_NONE      32833
#define ID_TOOLS_CAMERAIMAGER           32834
#define ID_VIEW_OUTLIERCLOUD            32835
#define ID_TOOLS_SURFACESMOOTHING       32837
#define ID_VIEW_CONNECTEDMESH_TEXTUREEDGELS 32843
#define ID_TOOLS_TEXTUREEDGEDETECTOR    32844
#define ID_TOOLS_HISTOGRAMEQUALISATION  32845
#define ID_VIEW_ZEROCROSSINGS_MEANCURVATURE 32854
#define ID_VIEW_ZEROCROSSINGS_GAUSSIANCURVATURE 32855
#define ID_VIEW_POINTEXTREMITIES_MAXIMA 32856
#define ID_VIEW_POINTEXTREMITIES_MINIMA 32857
#define ID_VIEW_POINTEXTREMITIES_SADDLES 32858
#define ID_TOOLS_CURVATUREMAP_EXPORTCOVARIANCES 32861
#define ID_TOOLS_CURVATUREMAP_CALCULATEFOCALSURFACES 32864
#define ID_TOOLS_CURVATUREMAP_DETECTUMBILICPOINTS 32865
#define ID_TOOLS_CURVATUREMAP_DETECTRIDGES 32866
#define ID_VIEW_COLOURMAP_N             32867
#define ID_VIEW_COLOURMAP_INTENSITIES   32868
#define ID_VIEW_COLOURMAP_GAUSSIANCURVATURE 32869
#define ID_VIEW_COLOURMAP_MEANCURVATURE 32870
#define ID_VIEW_COLOURMAP_CURVEDNESS    32871
#define ID_VIEW_COLOURMAP_SHAPEINDEX    32872
#define ID_VIEW_CONNECTEDMESH_PHOTOREALISTIC 32873
#define ID_VIEW_CURVATUREDIRECTIONS     32874
#define ID_VIEW_CURVATUREDIRECTIONS_RED 32875
#define ID_VIEW_CURVATUREDIRECTIONS_BLUE 32876
#define ID_VIEW_CURVATUREDIRECTIONS_ALL 32877
#define ID_VIEW_CURVATUREDIRECTIONS_NONE 32878
#define ID_VIEW_RIDGES                  32879
#define ID_VIEW_FLEXCORDS               32880
#define ID_VIEW_SYMMETRYPLANES_BODY     32881
#define ID_VIEW_SYMMETRYPLANES_ELLIPSOID 32882
#define ID_VIEW_SYMMETRYPLANES_TOOTHCUBE 32883
#define ID_VIEW_SYMMETRYPLANES_OCTAHEDRONDIAMOND 32884
#define ID_VIEW_SYMMETRYPLANES_BUMPYSPHERETETRAHEDRON 32885
#define ID_VIEW_SYMMETRYPLANES_NONE     32886

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_3D_CONTROLS                     1
#define _APS_NEXT_RESOURCE_VALUE        151
#define _APS_NEXT_COMMAND_VALUE         32887
#define _APS_NEXT_CONTROL_VALUE         1020
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
